### ISSUE TITLE
HAMT-like structure

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/microkelvin#37] opened 2021-01-26 12:22 UTC
We need a data structure similar to NStack that will allow the user to insert elements on random positions of the tree implemented for microkelvin.

All the other traits of NStack should be inherited by this data structure.

Optionally, if the effort impact is minimal, the data structure should have dynamic branching factor. We are, however, bound by Poseidon252 implementation with fixed arity - this way, dynamic arity will not be possible for now.

**Comment by krl** [comment] 2021-01-27 16:17
duplicate of https://github.com/dusk-network/dusk-hamt/issues/1

**Closed by krl** 2021-01-27 16:17 UTC
Labels: team:Core
